cloudposse/terraform-aws-rds-cluster

main.tf

* Remove duplicate attribute
* Remove `Aurora` from the description
* The module could be used to create any DB cluster including regular RDS for MySQL and Postgres, not only Aurora

Remove duplicate `vpc_security_group_ids`

---

main.tf
variables.tf

* Made database port configurable 
* Bumped `tf_label` version to `0.2.0`
* The module should work with both `MySQL` and `Postgres` `Aurora` which use different ports
* Bumped to the latest version of `tf_label`

Make database port configurable

---

main.tf
variables.tf

* Add support for `engine` and `engine_version` variables
* Easily enable `aurora`

Support `engine` and `engine_version` variables

---

README.md
docs/terraform.md
main.tf
variables.tf

* Make `zone_id` optional
* Not all applications require creating sub-domains for the DB master and replicas
* https://github.com/cloudposse/terraform-aws-rds-cluster/issues/29

Make `zone_id` optional

---

README.md
docs/terraform.md
variables.tf

* Make `admin_password` optional
* If `snapshot_identifier` is provided to restore cluster from the snapshot, `admin_password` is not required and TF should not ask for it

Make `admin_password` optional

---

README.md
docs/terraform.md
main.tf
variables.tf

* Add Aurora cluster [autoscaling](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Integrating.AutoScaling.html)
* To be able to scale the read replica count up/down depending on cluster utilization

Add cluster autoscaling

---

README.md
README.yaml
docs/terraform.md
main.tf
variables.tf

* Add cluster and reader DNS names
* The default DNS names can conflict with other database clusters when deployed together (e.g. DocumentDB for Codefresh on-prem)

Add cluster and reader DNS names

---

main.tf
variables.tf

`timeout_action` isn't passed through to the `aws_rds_cluster` resource when specified at the module level. This PR will fix that.

fix: respect timeout_action from scaling_configuration

---

README.md
docs/terraform.md
main.tf
variables.tf

Allow copy_tags_to_snapshot to be set to true via terraform.
Signed-off-by: Jon Whitcraft <jwhitcraft@mac.com>

Allow setting `copy_tags_to_snapshot` variable

---

README.md
docs/terraform.md
examples/complete/fixtures.us-west-1.tfvars
outputs.tf
variables.tf

Allow creation of a cluster without creation of a database
It is possible and acceptable to create a cluster first and add database(s) and user(s) later, but this module did not allow it before now

Allow creation of a cluster without creation of a database

---

main.tf

Fix for https://github.com/cloudposse/terraform-aws-rds-cluster/issues/63
The cluster_size or the instance_count should be independent of autoscaling_min_capacity as autoscaling_min_capacity is automatically taken care of by AWS through the autoscaling policy.
For example, when autoscaling is enabled:
if I specify:
```
cluster_size = 2
autoscaling_min_capacity = 1
```
terraform creates only one instance even though cluster_size is set to 2 , 
and if I specify:
```
cluster_size = 2
autoscaling_min_capacity = 2 
```
terraform spins up 2 instances but AWS autoscaling policy immediately spins up one more instance, which is not desired. 
This also breaks the terraform as it is not aware of the new instance that is created by AWS autoscaling policy.

fix(#63): instance_count to be independent of autoscaling_min_capacity

---

README.md
README.yaml
docs/terraform.md
examples/serverless_mysql/main.tf
main.tf
variables.tf

This PR introduces new option: `enable_http_endpoint` for aurora serverless engine.
As the option in terraform provider is no longer in beta 
- [reference](https://www.terraform.io/docs/providers/aws/r/rds_cluster.html).
related to: #54 #51

feat(enable_http_endpoint): added new enable_http_endpoint option for aurora serverless engine

---

README.md
docs/terraform.md
examples/complete/outputs.tf
main.tf
outputs.tf

* Fix outputs when `enabled=false`
* Change Security Group rules from inline to resources
* Fix outputs when `enabled=false`: `coalesce` will throw error when both parameters are empty
* Change Security Group rules from inline to resources: output the Security Group name, ID and ARN to allow adding other rules to the SG (which is not possible with the inline SG rules, and not possible to mix inline rules with resource-based rules)
* Closes #24

Fix outputs when `enabled=false`. Change Security Group rules from inline to resources

---

.github/workflows/auto-release.yml
README.md
README.yaml
docs/terraform.md
enhanced-monitoring.tf
examples/basic/main.tf
examples/basic/outputs.tf
examples/complete/fixtures.us-east-2.tfvars
examples/complete/variables.tf
examples/enhanced_monitoring/main.tf
examples/enhanced_monitoring/outputs.tf
examples/serverless_mysql/main.tf
examples/serverless_mysql/outputs.tf
examples/with_cluster_parameters/main.tf
examples/with_cluster_parameters/outputs.tf
main.tf
test/src/go.mod
variables.tf

* Add IAM role for enhanced monitoring
* Allow enhanced monitoring for the RDS cluster
* When the IAM role for enhanced monitoring is enabled (variable `enhanced_monitoring_role_enabled` is set to `true`), the module will create an IAM role for enhanced monitoring and assign the managed policy `AmazonRDSEnhancedMonitoringRole` to the role
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Monitoring.OS.html
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#monitoring_role_arn

Add IAM role for enhanced monitoring

---

main.tf

* DNS was changing when it shouldn't have been, it was the value of:
```
${var.name}-${local.cluster_dns_name}
```
I think this may have changed in https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/releases/tag/0.6.0
This changes the parameter to `dns_name` and upgrades the version to get a stable DNS record
* Fix broken DNS

Fixes DNS prepending var.name to local.cluster_dns_name

---

README.md
docs/terraform.md
versions.tf

v0.37.0 of this module added support for Aurora cluster cloning and
point-in-time restore [1] which itself was introduced in version
3.1.15 of the AWS provider[2] via the `restore_to_point_in_time`[3]
attribute.
This commits the dependancy on this module to track that requirement
for the newer AWS provider.
[1] https://github.com/cloudposse/terraform-aws-rds-cluster/pull/92
[2] https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md#3150-november-12-2020
[3] https://github.com/hashicorp/terraform-provider-aws/pull/7031

Support for cluster cloning requires AWS provider 3.1.15+

---

README.md
docs/terraform.md
main.tf
variables.tf

- Allow user to specify explicitly whether or not this should create a primary or secondary cluster
- Implicit selection based on `global_cluster_identifier` fails if the global cluster is being created at the same time as the primary and/or secondary cluster

Be explicit about primary/secondary cluster

---

main.tf

- Make parameter groups `create_before_destroy`
- Add explicit dependencies
- You cannot delete a parameter group while it is in use, but you can update a database with a new parameter group, so in order to change parameter groups, you need to create a new one, install it, then delete the old one. 
- Some update and destroy operations were failing because resources were being deleted in the wrong order.

create_before_destroy for parameter groups, explicit dependencies

---

README.md
docs/terraform.md
examples/with_cluster_parameters/main.tf

Prior value was invalid according to aws docs when trying to create a `aurora-mysql` based instance.
AWS Terraform Provider docs indicated: 
> engine - (Optional) The name of the database engine to be used for this DB cluster. Defaults to aurora. Valid Values: aurora, aurora-mysql, aurora-postgresql
Since the examples I used were to deploy `aurora-mysql` the engine should be set to this as well when the cluster family is set as follows:
```text
engine  = "aurora-mysql"
cluster_family  = "aurora-mysql5.7"
```
Adjust to `aurora-mysql` and this resolved the failure to deploy a new cluster based on the mysql engine.

fix: 🐛 adjust engine version in docs and readme to aurora-mysql

---

README.md
main.tf

* Ignore `engine_version` for rds instance in order to upgrade
* When the `engine_version` for the `aws_rds_cluster` is changed and applied, the db instances will be upgraded.
* There is a note on the [rds_cluster_instance#engine_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#engine_version) which states
> (Optional, Forces new resource) The database engine version. When managing the engine version in the cluster, it is recommended to add the [lifecycle `ignore_changes` configuration](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html#ignore_changes) for this argument to prevent Terraform from proposing changes to the instance engine version directly.
<details><summary>terraform plan</summary>
```diff
+/- …
```

Ignore `engine_version` for rds instance in order to upgrade without recreating db instances

---

.github/CODEOWNERS
.github/auto-release.yml
.github/mergify.yml
.github/workflows/auto-format.yml
.github/workflows/auto-release.yml
.github/workflows/validate-codeowners.yml
main.tf

* Add `apply_immediately` flag to the db instances 
* Currently you can only apply changes immediately to the cluster resource. However the `aws_rds_cluster_instance` resource also supports the `apply_immediately` flag.
* Use case: Attempting to change the instance types for the RDS cluster causes the changes to be staged pending the next maintenance window. This change allows you to perform the updates before then.

added apply_immediately support to cluster_instance resource

---

README.md
docs/terraform.md
main.tf
variables.tf

Fixes errors like:
Error: error creating RDS cluster: InvalidParameterCombination: Cannot specify user name for instance cluster replication cluster

Ignore admin credentials for snapshots/replicated clusters

---

README.md
docs/terraform.md
versions.tf

* c96d859 added performance_insights_retention_period, which is supported in AWS provider v3.63.0 onwards.
* Prevent issues with older cached aws providers
N/A

Update AWS provider minimum version

---

main.tf

* Prevent creating empty DNS replicas record when `cluster_size` < 1
* If the `cluster_size = 0` this would result in an attempt to create an empty DNS record, which is not permitted by the Route53 API
* Follow-up to changes done in https://github.com/cloudposse/terraform-aws-rds-cluster/pull/124

fix: prevent creating empty replicas record

---

README.md
outputs.tf

* Flag `master_username` output as sensitive
Running on Terraform Cloud
```
Terraform v0.14.5
Configuring remote state backend...
Initializing Terraform configuration...
Error: Output refers to sensitive values
on .terraform/modules/db/outputs.tf line 6:
6: output "master_username" {
Expressions used in outputs can only refer to sensitive values if the
sensitive attribute is true.
```
* https://www.terraform.io/upgrade-guides/0-14.html#sensitive-values-in-plan-output

Flag `master_username` output as sensitive

---

main.tf

* Restore original logic
* Previous logic was to create the record when module was not serverless
* Previous PR https://github.com/cloudposse/terraform-aws-rds-cluster/pull/124

Create dns record if not serverless

---

.github/auto-release.yml
main.tf

* Pass a value to db_instance_parameter_group_name argument when allow_major_version_upgrade is true.
* When absent, the upgrade process would fail with _InvalidParameterCombination_ exception thrown from AWS provider.
* closes #134 
* [Terraform aws_rds_cluster resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#db_instance_parameter_group_name)

Fix: Upgrading DB version fails with InvalidParameterCombination for instance parameter group

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/auto-context.yml
.github/workflows/auto-format.yml
.github/workflows/auto-readme.yml
.github/workflows/auto-release.yml
.github/workflows/chatops.yml
.github/workflows/validate-codeowners.yml
README.md
docs/terraform.md
examples/postgres/fixtures.us-east-2.tfvars
main.tf
outputs.tf
test/src/Makefile
test/src/examples_postgres_test.go
variables.tf

* Allow to create Activity Stream for RDS Cluster
Added by @nuru:
* Move PostgreSQL testing to proper test region (us-east-2)
* Fix expected subnet CIDR due to fewer availability zones in us-east-2 than us-east-1
* Increase test parallelism so that tests complete in under 60 minutes
* Can be used to enable and activity stream from the cluster module itself

Support for Activity Stream added

---

.github/workflows/release-branch.yml
.github/workflows/release-published.yml
enhanced-monitoring.tf
examples/complete/fixtures.us-east-2.tfvars
examples/complete/main.tf
examples/postgres/fixtures.us-east-2.tfvars
examples/postgres/main.tf
examples/serverless_mysql57/main.tf
examples/serverlessv2_postgres/main.tf
main.tf
outputs.tf

Support AWS Provider V5
Linter fixes
Maintenance
https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0

Support AWS Provider V5

---

README.md
examples/serverlessv2_postgres/fixtures.us-east-2.tfvars
main.tf

Add missing config to `aws_rds_cluster.secondary`
```
Error: creating RDS Cluster (<redacted>) Instance (<redacted>): InvalidDBClusterStateFault: Set the Serverless v2 scaling configuration on the parent DB cluster before creating a Serverless v2 DB instance.
│       status code: 400, request id:
```
Tested on my cluster and confirmed to work when a serverless configuration is provided.

Add serverlessv2 config to aws_rds_cluster.secondary

---

main.tf
variables.tf

- Fixes handling of `use_latest_restorable_time` and `restore_to_time` while preserving existing default values for backwards compatibility
- Original attempt at fixing this (https://github.com/cloudposse/terraform-aws-rds-cluster/pull/216) was insufficient
- Follow-up to original attempt: https://github.com/cloudposse/terraform-aws-rds-cluster/pull/216
- Correctly fixes https://github.com/cloudposse/terraform-aws-rds-cluster/issues/163

Fix conflicting `restore_to_point_in_time` attributes

---

main.tf

Fix too long identifier name without cluster recreation:
set `id_length_limit = 40` for
```tf
module "aurora" {
source  = "cloudposse/rds-cluster/aws"
version = "1.10.0"
...
id_length_limit = 40
}
``` 
will cause such recreation if final `module.this.id` will be between 40-60 characters
https://github.com/cloudposse/terraform-aws-rds-cluster/releases/tag/1.10.0 introduced `random_pet`, which adds 2 extra words on the top of `module.this.id`, and that exceed limit of 63 allowed characters for RDS names
```tf
╷
│ Error: creating RDS Cluster (company-staging-aurora-payments-ledger-service-aliases) Instance (company-staging-aurora-payments-ledger-service-aliases-promoted-piglet-1): operation error RDS: CreateDBInstance, https response error StatusCode: 400, RequestID: …
```

fix: Too long identifier name error

---

README.md
docs/terraform.md
main.tf
variables.tf

RDS cluster can be run in two network modes - IPV4 or DUAL.
Underlying module already supports this parameter
It can be mandatory to enable it to be able to connect from ipv6 only runtimes
Closes #175

Dual stack support

---

docs/terraform.md
outputs.tf

Fix the output
How it will look with this:
It does not need to be a join with a [*] this will cause error, just referring to it with the resource name will output everything as one object. 
See the Terraform provider docs https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_reserved_instance#attribute-reference

fix: reserved instance output

---

main.tf

This conditional check on whether or not to enable reserved instances is too restrictive. `contains(["mysql", "postgresql"], local.reserved_instance_engine)` is saying that only allow it if it is MySQL or PostgreSQL.
I think `contains` was originally meant to be like in the literal sense of "contains". Since in my case, I'm using `aurora-postgresql`, and it fails this check, yet it is one of the options for reserved instances.
`endswith` might be better, but it is TOO restrictive, seeing that there's so many options.
Additionally, Terraform will fail if user specifies the wrong engine type. There's no need for this check.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/rds_reserved_instance_offering

fix: reserved instances restrictions

---

main.tf

Using `local.is_regional_cluster` to determine whether or not it is Multi-AZ is not accurate. local.is_regional_cluster only checks if var.cluster_type == "regional", which determines if this is a regional vs global cluster
I could have a regional cluster, but it is NOT multi-az. One determining factor is how many instances in the cluster, if ever more than 1 in a single cluster, then it has to be in multiple AZs. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html
If I have a regional cluster, this thinks that it's ALWAYS multi-az, which is not true. 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html

fix: reserved instance multi_az setting

---

main.tf

RDS Reserved Instances multi AZ mode is never available for Aurora engines, see images on the console - this PR checks to ensure that it is set to false if the engine is Aurora:
That configuration isn't really applicable anyways since this statement from the AWS docs https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_WorkingWithReservedDBInstances.html:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_WorkingWithReservedDBInstances.html

fix: reserved instances, aurora rds specifics

---

main.tf
variables.tf
versions.tf

- Adds the `seconds_until_auto_pause` argument for `serverlessv2_scaling_configuration`
- Allow users to set this value to autopause clusters as needed
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#serverlessv2_scaling_configuration-argument-reference
- https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.81.0
- closes #238

feat: adds seconds_until_auto_pause argument
